# Reroute all App URLs under the dynamic path pattern to the React app
[[redirects]]
  from = "/app/*"
  to = "/app.html"
  status = 200

[build]
  environment = { REACT_APP_BASE_URL = "https://aut-bot.com", NODE_ENV = "production" }
  publish = "dist/"
  command = "yarn build"
