# Reroute all App URLs under the dynamic path pattern to the React app
[[redirects]]
  from = "/app/*"
  to = "/app.html"
  status = 200

[context.production]
  environment = { PRODUCTION_URL = "https://aut-bot.com" }

[build]
  environment = { NODE_ENV = "production" }
  publish = "dist/"
  command = "yarn build"
